/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotetris;

import javax.swing.JOptionPane;

/**
 *
 * @author mfss0
 */
public class Menu extends javax.swing.JFrame {
    private Game game;
    private GameWindow men;
    private FileManager flm;
    private RecordScoreWindow scr;
    private InstructionsWindow instr;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        flm = new FileManager();
        scr = new RecordScoreWindow();
        instr = new InstructionsWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserNamejlb = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        loadGameBtn = new javax.swing.JButton();
        instrBtn = new javax.swing.JButton();
        userNametxf = new java.awt.TextField();
        recordBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        UserNamejlb.setBackground(new java.awt.Color(223, 223, 42));
        UserNamejlb.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        UserNamejlb.setText("Username:");
        UserNamejlb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserNamejlb.setOpaque(true);
        jPanel1.add(UserNamejlb);
        UserNamejlb.setBounds(80, 230, 110, 40);

        playBtn.setBackground(new java.awt.Color(21, 108, 191));
        playBtn.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        playBtn.setForeground(new java.awt.Color(255, 255, 255));
        playBtn.setText("Play");
        playBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });
        jPanel1.add(playBtn);
        playBtn.setBounds(170, 340, 100, 60);

        loadGameBtn.setBackground(new java.awt.Color(153, 51, 255));
        loadGameBtn.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        loadGameBtn.setForeground(new java.awt.Color(255, 255, 255));
        loadGameBtn.setText("Load Game");
        loadGameBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loadGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loadGameBtn);
        loadGameBtn.setBounds(150, 410, 140, 60);

        instrBtn.setBackground(new java.awt.Color(225, 125, 25));
        instrBtn.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        instrBtn.setForeground(new java.awt.Color(255, 255, 255));
        instrBtn.setText("Instructions");
        instrBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        instrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instrBtnActionPerformed(evt);
            }
        });
        jPanel1.add(instrBtn);
        instrBtn.setBounds(140, 480, 160, 60);

        userNametxf.setBackground(new java.awt.Color(0, 0, 0));
        userNametxf.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        userNametxf.setForeground(new java.awt.Color(255, 255, 255));
        userNametxf.setText("Insert Name");
        jPanel1.add(userNametxf);
        userNametxf.setBounds(140, 280, 180, 30);

        recordBtn.setBackground(new java.awt.Color(0, 153, 0));
        recordBtn.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        recordBtn.setForeground(new java.awt.Color(255, 255, 255));
        recordBtn.setText("Records");
        recordBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtnActionPerformed(evt);
            }
        });
        jPanel1.add(recordBtn);
        recordBtn.setBounds(130, 550, 180, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotetris/img/fondo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 0, 500, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        game = new Game(userNametxf.getText());
        men = new GameWindow(game, scr);
        men.setVisible(true);
        
    }//GEN-LAST:event_playBtnActionPerformed

    private void loadGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameBtnActionPerformed
        game = flm.leerGame(userNametxf.getText().toUpperCase()+".bin");
        if (game == null)
               JOptionPane.showMessageDialog(this, "No se encontro una partida guardada con el usuario " + userNametxf.getText(), "No hay partida", JOptionPane.INFORMATION_MESSAGE);
        else{
            men = new GameWindow(game, scr);
            men.setVisible(true);
            }
    }//GEN-LAST:event_loadGameBtnActionPerformed

    private void recordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtnActionPerformed
        scr.update();
        scr.setVisible(true);
    }//GEN-LAST:event_recordBtnActionPerformed

    private void instrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instrBtnActionPerformed
        instr.setVisible(true);
    }//GEN-LAST:event_instrBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserNamejlb;
    private javax.swing.JButton instrBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadGameBtn;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton recordBtn;
    private java.awt.TextField userNametxf;
    // End of variables declaration//GEN-END:variables
}
